// <auto-generated />
using System;
using System.Collections.Generic;
using Abm.PD.Core.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abm.PD.Core.Repository.Migrations
{
    [DbContext(typeof(ProviderDirectoryDbContext))]
    [Migration("20260916140433_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_data_source");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_data_source_code");

                    b.ToTable("data_source", (string)null);
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.HasKey("Id")
                        .HasName("pk_resource");

                    b.ToTable("resource", (string)null);
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.SourceResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resource");

                    b.Property<DateTimeOffset>("ResourceLastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resource_last_updated");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource_type");

                    b.Property<string>("SourceResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_resource_id");

                    b.Property<Guid>("TargetResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_resource_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_source_resource");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_source_resource_data_source_id");

                    b.HasIndex("CorrelationId", "ResourceType", "SourceResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_source_resource_correlation_id_resource_type_source_resourc");

                    b.ToTable("source_resource", (string)null);
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.TaskBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("EndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at_utc");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("failure_count");

                    b.Property<Guid?>("LastCorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_correlation_id");

                    b.Property<DateTime?>("LastEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_end_utc");

                    b.Property<DateTime?>("LastStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_start_utc");

                    b.Property<int?>("MaxRunCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_run_count");

                    b.Property<int>("RunCount")
                        .HasColumnType("integer")
                        .HasColumnName("run_count");

                    b.Property<DateTime?>("StartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at_utc");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("StateReason")
                        .HasColumnType("text")
                        .HasColumnName("state_reason");

                    b.Property<TimeSpan>("TriggerEvery")
                        .HasColumnType("interval")
                        .HasColumnName("trigger_every");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_task");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_task_code");

                    b.ToTable("task", (string)null);

                    b.HasDiscriminator<int>("TypeId");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.TaskState", b =>
                {
                    b.Property<int>("TaskStateId")
                        .HasColumnType("integer")
                        .HasColumnName("task_state_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("TaskStateId")
                        .HasName("pk_task_state");

                    b.ToTable("task_state", (string)null);

                    b.HasData(
                        new
                        {
                            TaskStateId = 1,
                            Name = "Ready"
                        },
                        new
                        {
                            TaskStateId = 2,
                            Name = "InProgress"
                        },
                        new
                        {
                            TaskStateId = 3,
                            Name = "OnHold"
                        },
                        new
                        {
                            TaskStateId = 4,
                            Name = "Completed"
                        },
                        new
                        {
                            TaskStateId = 5,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.TaskType", b =>
                {
                    b.Property<int>("TaskTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("task_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("TaskTypeId")
                        .HasName("pk_task_type");

                    b.ToTable("task_type", (string)null);

                    b.HasData(
                        new
                        {
                            TaskTypeId = 1,
                            Name = "ExportTask"
                        },
                        new
                        {
                            TaskTypeId = 2,
                            Name = "MatchingTask"
                        },
                        new
                        {
                            TaskTypeId = 3,
                            Name = "ImportTask"
                        });
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.ExportTask", b =>
                {
                    b.HasBaseType("Abm.PD.Core.Domain.Entities.TaskBase");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_task_data_source_id");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.MatchingTask", b =>
                {
                    b.HasBaseType("Abm.PD.Core.Domain.Entities.TaskBase");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_data");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.SourceResource", b =>
                {
                    b.HasOne("Abm.PD.Core.Domain.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_source_resource_data_source_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.ExportTask", b =>
                {
                    b.HasOne("Abm.PD.Core.Domain.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_data_source_data_source_id");

                    b.OwnsOne("Abm.PD.Core.Domain.Entities.ExportParameter", "Parameter", b1 =>
                        {
                            b1.Property<int>("ExportTaskId")
                                .HasColumnType("integer")
                                .HasColumnName("export_task_id");

                            b1.Property<DateTimeOffset?>("Since")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("since");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("type");

                            b1.PrimitiveCollection<List<string>>("TypeFilterList")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("type_filter_list");

                            b1.HasKey("ExportTaskId")
                                .HasName("pk_export_task_parameter");

                            b1.ToTable("export_task_parameter", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExportTaskId")
                                .HasConstraintName("fk_export_task_parameter_task");
                        });

                    b.Navigation("DataSource");

                    b.Navigation("Parameter")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
