// <auto-generated />
using System;
using Abm.PD.Core.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abm.PD.Core.Repository.Migrations
{
    [DbContext(typeof(ProviderDirectoryDbContext))]
    [Migration("20260924071201_RemoveTaskAndResourceEntities")]
    partial class RemoveTaskAndResourceEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_data_source");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_data_source_code");

                    b.ToTable("data_source", (string)null);
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.SourceResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resource");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource_id");

                    b.Property<DateTimeOffset>("ResourceLastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resource_last_updated");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource_type");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_source_resource");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_source_resource_data_source_id");

                    b.HasIndex("CorrelationId", "ResourceType", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_source_resource_correlation_id_resource_type_resource_id");

                    b.ToTable("source_resource", (string)null);
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.SourceResource", b =>
                {
                    b.HasOne("Abm.PD.Core.Domain.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_source_resource_data_source_data_source_id");

                    b.Navigation("DataSource");
                });
#pragma warning restore 612, 618
        }
    }
}
