// <auto-generated />
using System;
using System.Collections.Generic;
using Abm.PD.Core.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abm.PD.Core.Repository.Migrations
{
    [DbContext(typeof(ProviderDirectoryDbContext))]
    [Migration("20260912132056_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.ProviderDataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_provider_data_source");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_data_source_code");

                    b.ToTable("provider_data_source", (string)null);
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.HasKey("Id")
                        .HasName("pk_resource");

                    b.ToTable("resource", (string)null);
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.TaskBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("LastEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_end");

                    b.Property<DateTime?>("LastStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_start");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("StateReason")
                        .HasColumnType("text")
                        .HasColumnName("state_reason");

                    b.Property<DateTime?>("ToEndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("to_end_at_utc");

                    b.Property<DateTime?>("ToStartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("to_start_at_utc");

                    b.Property<TimeSpan>("TriggerEvery")
                        .HasColumnType("interval")
                        .HasColumnName("trigger_every");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_task");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_task_code");

                    b.ToTable("task", (string)null);

                    b.HasDiscriminator<int>("TypeId");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.TaskState", b =>
                {
                    b.Property<int>("TaskStateId")
                        .HasColumnType("integer")
                        .HasColumnName("task_state_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("TaskStateId")
                        .HasName("pk_task_state");

                    b.ToTable("task_state", (string)null);

                    b.HasData(
                        new
                        {
                            TaskStateId = 1,
                            Name = "Ready"
                        },
                        new
                        {
                            TaskStateId = 2,
                            Name = "InProgress"
                        },
                        new
                        {
                            TaskStateId = 3,
                            Name = "OnHold"
                        },
                        new
                        {
                            TaskStateId = 4,
                            Name = "Completed"
                        },
                        new
                        {
                            TaskStateId = 5,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.TaskType", b =>
                {
                    b.Property<int>("TaskTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("task_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("TaskTypeId")
                        .HasName("pk_task_type");

                    b.ToTable("task_type", (string)null);

                    b.HasData(
                        new
                        {
                            TaskTypeId = 1,
                            Name = "BulkImport"
                        });
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.ExportLoaderTask", b =>
                {
                    b.HasBaseType("Abm.PD.Core.Domain.Entities.TaskBase");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Abm.PD.Core.Domain.Entities.ExportLoaderTask", b =>
                {
                    b.OwnsOne("Abm.PD.Core.Domain.Entities.ExportParameter", "Parameter", b1 =>
                        {
                            b1.Property<int>("ExportLoaderTaskId")
                                .HasColumnType("integer")
                                .HasColumnName("export_loader_task_id");

                            b1.Property<DateTimeOffset?>("Since")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("since");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("type");

                            b1.PrimitiveCollection<List<string>>("TypeFilterList")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("type_filter_list");

                            b1.HasKey("ExportLoaderTaskId")
                                .HasName("pk_export_loader_task_parameter");

                            b1.ToTable("export_loader_task_parameter", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExportLoaderTaskId")
                                .HasConstraintName("fk_export_loader_task_parameter_task");
                        });

                    b.Navigation("Parameter")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
