<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FhirNavigator" Version="1.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Abm.PD.BulkExport\Abm.PD.BulkExport.csproj" />
      <ProjectReference Include="..\Abm.PD.Core.Domain\Abm.PD.Core.Domain.csproj" />
    </ItemGroup>

</Project>
